"""
Stage 5 — Guardrail Validator (programmatic, no LLM). The safety-critical
stage: nothing generated by Stage 4a (v0) or Stage 4b (v1) touches the
database until it passes this static, allow-list-based check, regardless of
which stage produced it.

Defense in depth beyond this file (see AGENTIC_RAG_ARCHITECTURE.md §4 Stage 5
and db/init/03_agent_ro_role.sh): a dedicated read-only Postgres role, a
per-connection statement timeout + read-only transaction, and parameter
binding so extracted values are never string-interpolated into SQL text.
"""
import re

import sqlglot
from sqlglot import exp

from . import schema_loader

DEFAULT_ROW_LIMIT = 200
_PSYCOPG2_PARAM_RE = re.compile(r"%\(\w+\)s")


class GuardrailError(Exception):
    pass


def _parseable_copy(sql: str) -> str:
    """psycopg2's %(name)s pyformat placeholders aren't valid standalone SQL
    syntax — swap them for an innocuous string literal so sqlglot can build
    a structurally-accurate AST. The ORIGINAL sql (with placeholders intact)
    is what's actually returned/executed; this copy exists for parsing only."""
    return _PSYCOPG2_PARAM_RE.sub("'__PARAM__'", sql)


def _select_aliases(tree: exp.Select) -> set:
    """Names introduced by any SELECT list in the query — top-level AND
    nested (subqueries, derived tables) — e.g. `count(*) AS shipment_count`
    or a derived table's `created_at::date AS day`. Legitimately referenced
    by an outer ORDER BY/GROUP BY/HAVING or by `alias.column` from an
    enclosing join without being a real table column. sqlglot's exp.Column
    nodes don't distinguish "real column" from "reference back to an alias"
    at parse time, so both look identical to find_all(exp.Column).

    Walking every nested exp.Select (not just the outermost) matters in
    practice, not just in theory: a two-subquery FULL OUTER JOIN rewrite of
    the daily_volume_trend template (bounded date-range aggregates instead
    of an expensive unbounded generate_series — see
    AGENTIC_RAG_ARCHITECTURE.md §9) was being wrongly rejected as
    'unknown column: cnt' before this fix, because `cnt` was a derived
    table's internal alias, never captured by only scanning the outer
    SELECT list. This doesn't weaken the allow-list: an alias, at any
    nesting depth, can only ever refer to a value its own SELECT list
    already computed from already-checked real columns — it never grants
    access to anything new, the same reasoning as the top-level-only
    version this replaces."""
    aliases = set()
    for select in tree.find_all(exp.Select):
        aliases |= {e.alias for e in select.expressions if e.alias}
    return aliases


def validate_sql(sql: str, allowed_entity_keys: list) -> str:
    """Raises GuardrailError if `sql` does anything outside the allow-list
    derived from `allowed_entity_keys` (schema JSON entity/view keys).
    Returns the (possibly LIMIT-appended) original SQL, still carrying its
    %(name)s placeholders, ready for parameterized execution."""
    allowed_tables = {schema_loader.table_name(k) for k in allowed_entity_keys}
    allowed_columns = {"*"}
    for key in allowed_entity_keys:
        allowed_columns |= schema_loader.schema_fields(key)

    try:
        statements = sqlglot.parse(_parseable_copy(sql), read="postgres")
    except Exception as exc:
        raise GuardrailError(f"SQL failed to parse: {exc}") from exc

    statements = [s for s in statements if s is not None]
    if len(statements) != 1:
        raise GuardrailError(f"exactly one statement is allowed, got {len(statements)}")

    tree = statements[0]
    if not isinstance(tree, exp.Select):
        raise GuardrailError("only SELECT statements are allowed")

    # sqlglot has no single exp.Alter/exp.Grant base class — AlterTable is
    # the concrete node, and GRANT isn't part of its DML/DDL expression tree
    # at all (it fails to parse as anything but a top-level statement, which
    # the isinstance(tree, exp.Select) check above already rejects).
    for banned in (exp.Insert, exp.Update, exp.Delete, exp.Drop,
                   exp.AlterTable, exp.Create, exp.Into):
        if tree.find(banned):
            raise GuardrailError(f"{banned.__name__} operations are not allowed")

    tables = {t.name for t in tree.find_all(exp.Table)}
    if not tables:
        raise GuardrailError("query does not reference any table")
    if not tables <= allowed_tables:
        raise GuardrailError(
            f"query references tables outside the scoped allow-list: {tables - allowed_tables}"
        )

    columns = {c.name for c in tree.find_all(exp.Column)}
    unknown_columns = columns - allowed_columns - _select_aliases(tree)
    if unknown_columns:
        raise GuardrailError(f"query references unknown columns: {unknown_columns}")

    final_sql = sql.strip()
    if not tree.args.get("limit"):
        final_sql += f"\nLIMIT {DEFAULT_ROW_LIMIT}"

    return final_sql
